const CATALOG = [
  {
    id: "el1",
    name: "Футболка UZcotton мужская",
    img: "img/catalog/UZcotton.png",
    oldPrice: 1051,
    newPrice: 522,
    availability: 2,
    color: "белый",
    size: 56,
    sortingCenter: "OOO Вайлдберриз",
    check: false,
  },
  {
    id: "el2",
    name: "Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe",
    img: "img/catalog/case.png",
    oldPrice: 2300047,
    newPrice: 210047,
    availability: 250,
    color: "прозрачный",
    size: "",
    sortingCenter: "OOO Мегапрофстиль",
    check: false,
  },
  {
    id: "el3",
    name: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные, Faber-Castell ',
    img: "img/catalog/pencil.png",
    oldPrice: 950,
    newPrice: 494,
    availability: 2,
    color: "",
    size: "",
    sortingCenter: "OOO Вайлдберриз",
    check: false,
  },
];

const CATALOGEMPTY = [
  {
    id: "el1",
    name: "Футболка UZcotton мужская",
    img: "img/catalog/UZcotton.png",
    oldPrice: 1051,
    newPrice: 522,
    availability: 2,
    color: "белый",
    size: 56,
    sortingCenter: "OOO Вайлдберриз",
    check: false,
  },
  {
    id: "el2",
    name: "Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe",
    img: "img/catalog/case.png",
    oldPrice: 2300047,
    newPrice: 210047,
    availability: 250,
    color: "прозрачный",
    size: "",
    sortingCenter: "OOO Мегапрофстиль",
    check: false,
  },
  {
    id: "el3",
    name: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные, Faber-Castell ',
    img: "img/catalog/pencil.png",
    oldPrice: 950,
    newPrice: 494,
    availability: 2,
    color: "",
    size: 56,
    sortingCenter: "OOO Вайлдберриз",
    check: false,
  },
];
